import { createFileRoute } from "@tanstack/react-router";
import { CandlestickChart, CheckCircle2, ShieldAlert, BookOpen } from "lucide-react";
import { MemberShell } from "@/components/brand/member-shell";
import { CourseGrid } from "@/components/brand/course-grid";
import { tradingCourses, checklist, journalPreview } from "@/data/member";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
export const Route = createFileRoute("/trading")({ component: TradingPage });
function TradingPage() { return <MemberShell><div className="mx-auto max-w-7xl px-4 py-8 sm:px-8 lg:py-12"><div className="flex flex-col gap-8"><header><p className="eyebrow text-gold">The 1% Club · Skill development</p><h1 className="display-xl mt-3">Trading Room</h1><p className="mt-3 max-w-2xl text-base leading-relaxed text-muted-foreground">Control your mind before you try to control the market.</p></header><Alert className="border-gold/40 bg-charcoal"><ShieldAlert className="size-4 text-gold" /><AlertTitle>Educational notice</AlertTitle><AlertDescription>The Trading Room is for education and skill development. Trading involves risk, and the 1% Club does not guarantee profits or financial results.</AlertDescription></Alert><div><p className="eyebrow text-muted-foreground">Learning categories</p><h2 className="display-md mt-2">Build your process</h2></div><CourseGrid courses={tradingCourses} /><section className="grid gap-4 lg:grid-cols-3"><Card variant="bordered"><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="size-4 text-forest" /> Trading checklist</CardTitle></CardHeader><CardContent><ul className="flex flex-col gap-3">{checklist.map((item) => <li key={item} className="flex gap-2 text-sm text-muted-foreground"><span className="mt-1 size-3 shrink-0 rounded-full border border-border" />{item}</li>)}</ul></CardContent></Card><Card variant="bordered"><CardHeader><CardTitle className="flex items-center gap-2"><BookOpen className="size-4 text-gold" /> Trading journal</CardTitle><CardDescription>A private practice preview.</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-2">{journalPreview.map((field) => <div key={field} className="rounded-md border border-border bg-charcoal px-3 py-2 text-xs text-muted-foreground">{field}</div>)}</div></CardContent></Card><div className="flex flex-col gap-4"><Card variant="gold"><CardHeader><CardTitle>Risk comes before reward.</CardTitle></CardHeader></Card><Card variant="crimson"><CardHeader><CardTitle>Practise the process before risking real money.</CardTitle></CardHeader></Card></div></section></div></div></MemberShell>; }
